#%RAML 0.8
title: studentAPI
version: 1.0.0

/campus:
  /prospect: 
    post:
      body:
        application/json:
      responses:
        200:
          body:
            application/json:
  /lead:
    post:
      body:
        application/json:
      responses:
        200:
          body:
            application/json:
  